import type { ReactNode } from 'react';

import type { Metadata } from 'next';
import { Cinzel, Poppins } from 'next/font/google';
import localFont from 'next/font/local';

import '@/app/globals.css';

import './globals.css';
import { Providers } from './provider/Provider';

const geistSans = localFont({
    src: './fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900'
});

const geistMono = localFont({
    src: './fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
    weight: '100 900'
});

const cinzel = Cinzel({
    subsets: ['latin'],
    weight: ['400', '700'],
    variable: '--font-cinzel'
});

const poppins = Poppins({
    subsets: ['latin'],
    weight: ['400', '500', '600', '700'],
    variable: '--font-poppins'
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

const Layout = ({ children }: Readonly<{ children: ReactNode }>) => {
    return (
        <html suppressHydrationWarning lang='en'>
            <body className={`${geistSans.variable} ${geistMono.variable} ${cinzel.variable} ${poppins.variable}`}>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
};

export default Layout;
